image: nachomillangarcia/prometheus_aws_cost_exporter:latest
args:
  - --host
  - 0.0.0.0
svcAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "5000"
  prometheus.io/scheme: "http"
  prometheus.io/path: "/metrics"
podAnnotations:
env:
tagFilters:
  # filterName:
  #   tagName1: tagValue1
  #   tagName2: tagValue2
  test:
    Tag1: value1
    Tag2: value2
